// Copyright (c) 2026 Glenn Watson. All rights reserved.
// Glenn Watson licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

// <auto-generated/> from a name list; regenerate rather than editing by hand.

namespace HyperPdfLibrary.Objects;

/// <summary>PDF names the library looks up. Each has a fixed id in every document's name table.</summary>
public enum KnownName
{
    /// <summary>No name.</summary>
    None = 0,

    /// <summary>The <c>/Type</c> name.</summary>
    Type = 1,

    /// <summary>The <c>/Subtype</c> name.</summary>
    Subtype = 2,

    /// <summary>The <c>/Length</c> name.</summary>
    Length = 3,

    /// <summary>The <c>/Filter</c> name.</summary>
    Filter = 4,

    /// <summary>The <c>/DecodeParms</c> name.</summary>
    DecodeParms = 5,

    /// <summary>The <c>/F</c> name.</summary>
    F = 6,

    /// <summary>The <c>/FFilter</c> name.</summary>
    FFilter = 7,

    /// <summary>The <c>/FDecodeParms</c> name.</summary>
    FDecodeParms = 8,

    /// <summary>The <c>/DL</c> name.</summary>
    DL = 9,

    /// <summary>The <c>/N</c> name.</summary>
    N = 10,

    /// <summary>The <c>/First</c> name.</summary>
    First = 11,

    /// <summary>The <c>/Extends</c> name.</summary>
    Extends = 12,

    /// <summary>The <c>/Size</c> name.</summary>
    Size = 13,

    /// <summary>The <c>/Prev</c> name.</summary>
    Prev = 14,

    /// <summary>The <c>/Root</c> name.</summary>
    Root = 15,

    /// <summary>The <c>/Info</c> name.</summary>
    Info = 16,

    /// <summary>The <c>/ID</c> name.</summary>
    ID = 17,

    /// <summary>The <c>/Encrypt</c> name.</summary>
    Encrypt = 18,

    /// <summary>The <c>/XRefStm</c> name.</summary>
    XRefStm = 19,

    /// <summary>The <c>/Index</c> name.</summary>
    Index = 20,

    /// <summary>The <c>/W</c> name.</summary>
    W = 21,

    /// <summary>The <c>/ObjStm</c> name.</summary>
    ObjStm = 22,

    /// <summary>The <c>/XRef</c> name.</summary>
    XRef = 23,

    /// <summary>The <c>/Catalog</c> name.</summary>
    Catalog = 24,

    /// <summary>The <c>/Pages</c> name.</summary>
    Pages = 25,

    /// <summary>The <c>/Page</c> name.</summary>
    Page = 26,

    /// <summary>The <c>/Kids</c> name.</summary>
    Kids = 27,

    /// <summary>The <c>/Parent</c> name.</summary>
    Parent = 28,

    /// <summary>The <c>/Count</c> name.</summary>
    Count = 29,

    /// <summary>The <c>/MediaBox</c> name.</summary>
    MediaBox = 30,

    /// <summary>The <c>/CropBox</c> name.</summary>
    CropBox = 31,

    /// <summary>The <c>/BleedBox</c> name.</summary>
    BleedBox = 32,

    /// <summary>The <c>/TrimBox</c> name.</summary>
    TrimBox = 33,

    /// <summary>The <c>/ArtBox</c> name.</summary>
    ArtBox = 34,

    /// <summary>The <c>/Rotate</c> name.</summary>
    Rotate = 35,

    /// <summary>The <c>/Resources</c> name.</summary>
    Resources = 36,

    /// <summary>The <c>/Contents</c> name.</summary>
    Contents = 37,

    /// <summary>The <c>/Annots</c> name.</summary>
    Annots = 38,

    /// <summary>The <c>/UserUnit</c> name.</summary>
    UserUnit = 39,

    /// <summary>The <c>/Group</c> name.</summary>
    Group = 40,

    /// <summary>The <c>/Metadata</c> name.</summary>
    Metadata = 41,

    /// <summary>The <c>/PageLabels</c> name.</summary>
    PageLabels = 42,

    /// <summary>The <c>/Outlines</c> name.</summary>
    Outlines = 43,

    /// <summary>The <c>/Dests</c> name.</summary>
    Dests = 44,

    /// <summary>The <c>/Names</c> name.</summary>
    Names = 45,

    /// <summary>The <c>/OpenAction</c> name.</summary>
    OpenAction = 46,

    /// <summary>The <c>/PageMode</c> name.</summary>
    PageMode = 47,

    /// <summary>The <c>/Version</c> name.</summary>
    Version = 48,

    /// <summary>The <c>/Lang</c> name.</summary>
    Lang = 49,

    /// <summary>The <c>/StructTreeRoot</c> name.</summary>
    StructTreeRoot = 50,

    /// <summary>The <c>/MarkInfo</c> name.</summary>
    MarkInfo = 51,

    /// <summary>The <c>/AcroForm</c> name.</summary>
    AcroForm = 52,

    /// <summary>The <c>/OCProperties</c> name.</summary>
    OCProperties = 53,

    /// <summary>The <c>/Nums</c> name.</summary>
    Nums = 54,

    /// <summary>The <c>/Limits</c> name.</summary>
    Limits = 55,

    /// <summary>The <c>/ViewerPreferences</c> name.</summary>
    ViewerPreferences = 56,

    /// <summary>The <c>/Collection</c> name.</summary>
    Collection = 57,

    /// <summary>The <c>/Perms</c> name.</summary>
    Perms = 58,

    /// <summary>The <c>/Extensions</c> name.</summary>
    Extensions = 59,

    /// <summary>The <c>/NeedsRendering</c> name.</summary>
    NeedsRendering = 60,

    /// <summary>The <c>/XFA</c> name.</summary>
    XFA = 61,

    /// <summary>The <c>/Tabs</c> name.</summary>
    Tabs = 62,

    /// <summary>The <c>/StructParents</c> name.</summary>
    StructParents = 63,

    /// <summary>The <c>/StructParent</c> name.</summary>
    StructParent = 64,

    /// <summary>The <c>/S</c> name.</summary>
    S = 65,

    /// <summary>The <c>/P</c> name.</summary>
    P = 66,

    /// <summary>The <c>/St</c> name.</summary>
    St = 67,

    /// <summary>The <c>/D</c> name.</summary>
    D = 68,

    /// <summary>The <c>/R</c> name.</summary>
    R = 69,

    /// <summary>The <c>/A</c> name.</summary>
    A = 70,

    /// <summary>The <c>/Title</c> name.</summary>
    Title = 71,

    /// <summary>The <c>/Author</c> name.</summary>
    Author = 72,

    /// <summary>The <c>/Subject</c> name.</summary>
    Subject = 73,

    /// <summary>The <c>/Keywords</c> name.</summary>
    Keywords = 74,

    /// <summary>The <c>/Creator</c> name.</summary>
    Creator = 75,

    /// <summary>The <c>/Producer</c> name.</summary>
    Producer = 76,

    /// <summary>The <c>/CreationDate</c> name.</summary>
    CreationDate = 77,

    /// <summary>The <c>/ModDate</c> name.</summary>
    ModDate = 78,

    /// <summary>The <c>/Trapped</c> name.</summary>
    Trapped = 79,

    /// <summary>The <c>/Last</c> name.</summary>
    Last = 80,

    /// <summary>The <c>/Next</c> name.</summary>
    Next = 81,

    /// <summary>The <c>/Dest</c> name.</summary>
    Dest = 82,

    /// <summary>The <c>/SE</c> name.</summary>
    SE = 83,

    /// <summary>The <c>/C</c> name.</summary>
    C = 84,

    /// <summary>The <c>/URI</c> name.</summary>
    URI = 85,

    /// <summary>The <c>/GoTo</c> name.</summary>
    GoTo = 86,

    /// <summary>The <c>/GoToR</c> name.</summary>
    GoToR = 87,

    /// <summary>The <c>/GoToE</c> name.</summary>
    GoToE = 88,

    /// <summary>The <c>/Launch</c> name.</summary>
    Launch = 89,

    /// <summary>The <c>/Named</c> name.</summary>
    Named = 90,

    /// <summary>The <c>/JavaScript</c> name.</summary>
    JavaScript = 91,

    /// <summary>The <c>/JS</c> name.</summary>
    JS = 92,

    /// <summary>The <c>/NewWindow</c> name.</summary>
    NewWindow = 93,

    /// <summary>The <c>/Win</c> name.</summary>
    Win = 94,

    /// <summary>The <c>/Unix</c> name.</summary>
    Unix = 95,

    /// <summary>The <c>/Mac</c> name.</summary>
    Mac = 96,

    /// <summary>The <c>/ResetForm</c> name.</summary>
    ResetForm = 97,

    /// <summary>The <c>/SubmitForm</c> name.</summary>
    SubmitForm = 98,

    /// <summary>The <c>/ImportData</c> name.</summary>
    ImportData = 99,

    /// <summary>The <c>/Hide</c> name.</summary>
    Hide = 100,

    /// <summary>The <c>/AA</c> name.</summary>
    AA = 101,

    /// <summary>The <c>/Base</c> name.</summary>
    Base = 102,

    /// <summary>The <c>/XYZ</c> name.</summary>
    XYZ = 103,

    /// <summary>The <c>/Fit</c> name.</summary>
    Fit = 104,

    /// <summary>The <c>/FitH</c> name.</summary>
    FitH = 105,

    /// <summary>The <c>/FitV</c> name.</summary>
    FitV = 106,

    /// <summary>The <c>/FitR</c> name.</summary>
    FitR = 107,

    /// <summary>The <c>/FitB</c> name.</summary>
    FitB = 108,

    /// <summary>The <c>/FitBH</c> name.</summary>
    FitBH = 109,

    /// <summary>The <c>/FitBV</c> name.</summary>
    FitBV = 110,

    /// <summary>The <c>/Annot</c> name.</summary>
    Annot = 111,

    /// <summary>The <c>/Rect</c> name.</summary>
    Rect = 112,

    /// <summary>The <c>/QuadPoints</c> name.</summary>
    QuadPoints = 113,

    /// <summary>The <c>/InkList</c> name.</summary>
    InkList = 114,

    /// <summary>The <c>/Vertices</c> name.</summary>
    Vertices = 115,

    /// <summary>The <c>/L</c> name.</summary>
    L = 116,

    /// <summary>The <c>/LE</c> name.</summary>
    LE = 117,

    /// <summary>The <c>/IC</c> name.</summary>
    IC = 118,

    /// <summary>The <c>/BS</c> name.</summary>
    BS = 119,

    /// <summary>The <c>/Border</c> name.</summary>
    Border = 120,

    /// <summary>The <c>/BE</c> name.</summary>
    BE = 121,

    /// <summary>The <c>/AP</c> name.</summary>
    AP = 122,

    /// <summary>The <c>/AS</c> name.</summary>
    AS = 123,

    /// <summary>The <c>/NM</c> name.</summary>
    NM = 124,

    /// <summary>The <c>/M</c> name.</summary>
    M = 125,

    /// <summary>The <c>/T</c> name.</summary>
    T = 126,

    /// <summary>The <c>/Popup</c> name.</summary>
    Popup = 127,

    /// <summary>The <c>/Open</c> name.</summary>
    Open = 128,

    /// <summary>The <c>/IRT</c> name.</summary>
    IRT = 129,

    /// <summary>The <c>/RT</c> name.</summary>
    RT = 130,

    /// <summary>The <c>/State</c> name.</summary>
    State = 131,

    /// <summary>The <c>/StateModel</c> name.</summary>
    StateModel = 132,

    /// <summary>The <c>/RD</c> name.</summary>
    RD = 133,

    /// <summary>The <c>/DA</c> name.</summary>
    DA = 134,

    /// <summary>The <c>/DS</c> name.</summary>
    DS = 135,

    /// <summary>The <c>/Q</c> name.</summary>
    Q = 136,

    /// <summary>The <c>/RC</c> name.</summary>
    RC = 137,

    /// <summary>The <c>/CL</c> name.</summary>
    CL = 138,

    /// <summary>The <c>/IT</c> name.</summary>
    IT = 139,

    /// <summary>The <c>/Name</c> name.</summary>
    Name = 140,

    /// <summary>The <c>/Link</c> name.</summary>
    Link = 141,

    /// <summary>The <c>/Text</c> name.</summary>
    Text = 142,

    /// <summary>The <c>/FreeText</c> name.</summary>
    FreeText = 143,

    /// <summary>The <c>/Line</c> name.</summary>
    Line = 144,

    /// <summary>The <c>/Square</c> name.</summary>
    Square = 145,

    /// <summary>The <c>/Circle</c> name.</summary>
    Circle = 146,

    /// <summary>The <c>/Polygon</c> name.</summary>
    Polygon = 147,

    /// <summary>The <c>/PolyLine</c> name.</summary>
    PolyLine = 148,

    /// <summary>The <c>/Highlight</c> name.</summary>
    Highlight = 149,

    /// <summary>The <c>/Underline</c> name.</summary>
    Underline = 150,

    /// <summary>The <c>/Squiggly</c> name.</summary>
    Squiggly = 151,

    /// <summary>The <c>/StrikeOut</c> name.</summary>
    StrikeOut = 152,

    /// <summary>The <c>/Stamp</c> name.</summary>
    Stamp = 153,

    /// <summary>The <c>/Caret</c> name.</summary>
    Caret = 154,

    /// <summary>The <c>/Ink</c> name.</summary>
    Ink = 155,

    /// <summary>The <c>/FileAttachment</c> name.</summary>
    FileAttachment = 156,

    /// <summary>The <c>/Sound</c> name.</summary>
    Sound = 157,

    /// <summary>The <c>/Movie</c> name.</summary>
    Movie = 158,

    /// <summary>The <c>/Widget</c> name.</summary>
    Widget = 159,

    /// <summary>The <c>/Screen</c> name.</summary>
    Screen = 160,

    /// <summary>The <c>/PrinterMark</c> name.</summary>
    PrinterMark = 161,

    /// <summary>The <c>/TrapNet</c> name.</summary>
    TrapNet = 162,

    /// <summary>The <c>/Watermark</c> name.</summary>
    Watermark = 163,

    /// <summary>The <c>/Redact</c> name.</summary>
    Redact = 164,

    /// <summary>The <c>/Projection</c> name.</summary>
    Projection = 165,

    /// <summary>The <c>/RichMedia</c> name.</summary>
    RichMedia = 166,

    /// <summary>The <c>/3D</c> name.</summary>
    ThreeD = 167,

    /// <summary>The <c>/B</c> name.</summary>
    B = 168,

    /// <summary>The <c>/U</c> name.</summary>
    U = 169,

    /// <summary>The <c>/None</c> name.</summary>
    NoneName = 170,

    /// <summary>The <c>/Diamond</c> name.</summary>
    Diamond = 171,

    /// <summary>The <c>/OpenArrow</c> name.</summary>
    OpenArrow = 172,

    /// <summary>The <c>/ClosedArrow</c> name.</summary>
    ClosedArrow = 173,

    /// <summary>The <c>/Butt</c> name.</summary>
    Butt = 174,

    /// <summary>The <c>/ROpenArrow</c> name.</summary>
    ROpenArrow = 175,

    /// <summary>The <c>/RClosedArrow</c> name.</summary>
    RClosedArrow = 176,

    /// <summary>The <c>/Slash</c> name.</summary>
    Slash = 177,

    /// <summary>The <c>/Reply</c> name.</summary>
    Reply = 178,

    /// <summary>The <c>/Measure</c> name.</summary>
    Measure = 179,

    /// <summary>The <c>/VP</c> name.</summary>
    VP = 180,

    /// <summary>The <c>/H</c> name.</summary>
    H = 181,

    /// <summary>The <c>/O</c> name.</summary>
    O = 182,

    /// <summary>The <c>/Fields</c> name.</summary>
    Fields = 183,

    /// <summary>The <c>/FT</c> name.</summary>
    FT = 184,

    /// <summary>The <c>/Tx</c> name.</summary>
    Tx = 185,

    /// <summary>The <c>/Btn</c> name.</summary>
    Btn = 186,

    /// <summary>The <c>/Ch</c> name.</summary>
    Ch = 187,

    /// <summary>The <c>/Sig</c> name.</summary>
    Sig = 188,

    /// <summary>The <c>/Ff</c> name.</summary>
    Ff = 189,

    /// <summary>The <c>/V</c> name.</summary>
    V = 190,

    /// <summary>The <c>/DV</c> name.</summary>
    DV = 191,

    /// <summary>The <c>/Opt</c> name.</summary>
    Opt = 192,

    /// <summary>The <c>/TU</c> name.</summary>
    TU = 193,

    /// <summary>The <c>/TM</c> name.</summary>
    TM = 194,

    /// <summary>The <c>/MK</c> name.</summary>
    MK = 195,

    /// <summary>The <c>/MaxLen</c> name.</summary>
    MaxLen = 196,

    /// <summary>The <c>/NeedAppearances</c> name.</summary>
    NeedAppearances = 197,

    /// <summary>The <c>/DR</c> name.</summary>
    DR = 198,

    /// <summary>The <c>/CO</c> name.</summary>
    CO = 199,

    /// <summary>The <c>/Off</c> name.</summary>
    Off = 200,

    /// <summary>The <c>/Yes</c> name.</summary>
    Yes = 201,

    /// <summary>The <c>/TI</c> name.</summary>
    TI = 202,

    /// <summary>The <c>/I</c> name.</summary>
    I = 203,

    /// <summary>The <c>/SigFlags</c> name.</summary>
    SigFlags = 204,

    /// <summary>The <c>/Lock</c> name.</summary>
    Lock = 205,

    /// <summary>The <c>/SV</c> name.</summary>
    SV = 206,

    /// <summary>The <c>/ByteRange</c> name.</summary>
    ByteRange = 207,

    /// <summary>The <c>/SubFilter</c> name.</summary>
    SubFilter = 208,

    /// <summary>The <c>/Cert</c> name.</summary>
    Cert = 209,

    /// <summary>The <c>/Reason</c> name.</summary>
    Reason = 210,

    /// <summary>The <c>/Location</c> name.</summary>
    Location = 211,

    /// <summary>The <c>/ContactInfo</c> name.</summary>
    ContactInfo = 212,

    /// <summary>The <c>/Reference</c> name.</summary>
    Reference = 213,

    /// <summary>The <c>/DocMDP</c> name.</summary>
    DocMDP = 214,

    /// <summary>The <c>/DSS</c> name.</summary>
    DSS = 215,

    /// <summary>The <c>/VRI</c> name.</summary>
    VRI = 216,

    /// <summary>The <c>/TransformMethod</c> name.</summary>
    TransformMethod = 217,

    /// <summary>The <c>/TransformParams</c> name.</summary>
    TransformParams = 218,

    /// <summary>The <c>/EmbeddedFiles</c> name.</summary>
    EmbeddedFiles = 219,

    /// <summary>The <c>/EmbeddedFile</c> name.</summary>
    EmbeddedFile = 220,

    /// <summary>The <c>/Filespec</c> name.</summary>
    Filespec = 221,

    /// <summary>The <c>/UF</c> name.</summary>
    UF = 222,

    /// <summary>The <c>/EF</c> name.</summary>
    EF = 223,

    /// <summary>The <c>/Desc</c> name.</summary>
    Desc = 224,

    /// <summary>The <c>/Params</c> name.</summary>
    Params = 225,

    /// <summary>The <c>/AF</c> name.</summary>
    AF = 226,

    /// <summary>The <c>/CheckSum</c> name.</summary>
    CheckSum = 227,

    /// <summary>The <c>/ExtGState</c> name.</summary>
    ExtGState = 228,

    /// <summary>The <c>/ColorSpace</c> name.</summary>
    ColorSpace = 229,

    /// <summary>The <c>/Pattern</c> name.</summary>
    Pattern = 230,

    /// <summary>The <c>/Shading</c> name.</summary>
    Shading = 231,

    /// <summary>The <c>/XObject</c> name.</summary>
    XObject = 232,

    /// <summary>The <c>/Font</c> name.</summary>
    Font = 233,

    /// <summary>The <c>/ProcSet</c> name.</summary>
    ProcSet = 234,

    /// <summary>The <c>/Properties</c> name.</summary>
    Properties = 235,

    /// <summary>The <c>/Image</c> name.</summary>
    Image = 236,

    /// <summary>The <c>/Form</c> name.</summary>
    Form = 237,

    /// <summary>The <c>/PS</c> name.</summary>
    PS = 238,

    /// <summary>The <c>/BBox</c> name.</summary>
    BBox = 239,

    /// <summary>The <c>/Matrix</c> name.</summary>
    Matrix = 240,

    /// <summary>The <c>/Width</c> name.</summary>
    Width = 241,

    /// <summary>The <c>/Height</c> name.</summary>
    Height = 242,

    /// <summary>The <c>/BitsPerComponent</c> name.</summary>
    BitsPerComponent = 243,

    /// <summary>The <c>/ImageMask</c> name.</summary>
    ImageMask = 244,

    /// <summary>The <c>/Mask</c> name.</summary>
    Mask = 245,

    /// <summary>The <c>/SMask</c> name.</summary>
    SMask = 246,

    /// <summary>The <c>/Decode</c> name.</summary>
    Decode = 247,

    /// <summary>The <c>/Interpolate</c> name.</summary>
    Interpolate = 248,

    /// <summary>The <c>/SMaskInData</c> name.</summary>
    SMaskInData = 249,

    /// <summary>The <c>/Intent</c> name.</summary>
    Intent = 250,

    /// <summary>The <c>/Alternates</c> name.</summary>
    Alternates = 251,

    /// <summary>The <c>/OC</c> name.</summary>
    OC = 252,

    /// <summary>The <c>/Ref</c> name.</summary>
    Ref = 253,

    /// <summary>The <c>/OPI</c> name.</summary>
    OPI = 254,

    /// <summary>The <c>/Transparency</c> name.</summary>
    Transparency = 255,

    /// <summary>The <c>/CS</c> name.</summary>
    CS = 256,

    /// <summary>The <c>/K</c> name.</summary>
    K = 257,

    /// <summary>The <c>/LW</c> name.</summary>
    LW = 258,

    /// <summary>The <c>/LC</c> name.</summary>
    LC = 259,

    /// <summary>The <c>/LJ</c> name.</summary>
    LJ = 260,

    /// <summary>The <c>/ML</c> name.</summary>
    ML = 261,

    /// <summary>The <c>/RI</c> name.</summary>
    RI = 262,

    /// <summary>The <c>/OP</c> name.</summary>
    OP = 263,

    /// <summary>The <c>/op</c> name.</summary>
    FillOverprint = 264,

    /// <summary>The <c>/OPM</c> name.</summary>
    OPM = 265,

    /// <summary>The <c>/BG</c> name.</summary>
    BG = 266,

    /// <summary>The <c>/BG2</c> name.</summary>
    BG2 = 267,

    /// <summary>The <c>/UCR</c> name.</summary>
    UCR = 268,

    /// <summary>The <c>/UCR2</c> name.</summary>
    UCR2 = 269,

    /// <summary>The <c>/TR</c> name.</summary>
    TR = 270,

    /// <summary>The <c>/TR2</c> name.</summary>
    TR2 = 271,

    /// <summary>The <c>/HT</c> name.</summary>
    HT = 272,

    /// <summary>The <c>/FL</c> name.</summary>
    FL = 273,

    /// <summary>The <c>/SM</c> name.</summary>
    SM = 274,

    /// <summary>The <c>/SA</c> name.</summary>
    SA = 275,

    /// <summary>The <c>/BM</c> name.</summary>
    BM = 276,

    /// <summary>The <c>/CA</c> name.</summary>
    CA = 277,

    /// <summary>The <c>/ca</c> name.</summary>
    FillAlpha = 278,

    /// <summary>The <c>/AIS</c> name.</summary>
    AIS = 279,

    /// <summary>The <c>/TK</c> name.</summary>
    TK = 280,

    /// <summary>The <c>/Luminosity</c> name.</summary>
    Luminosity = 281,

    /// <summary>The <c>/Alpha</c> name.</summary>
    Alpha = 282,

    /// <summary>The <c>/G</c> name.</summary>
    G = 283,

    /// <summary>The <c>/BC</c> name.</summary>
    BC = 284,

    /// <summary>The <c>/Normal</c> name.</summary>
    Normal = 285,

    /// <summary>The <c>/Compatible</c> name.</summary>
    Compatible = 286,

    /// <summary>The <c>/Multiply</c> name.</summary>
    Multiply = 287,

    /// <summary>The <c>/Overlay</c> name.</summary>
    Overlay = 288,

    /// <summary>The <c>/Darken</c> name.</summary>
    Darken = 289,

    /// <summary>The <c>/Lighten</c> name.</summary>
    Lighten = 290,

    /// <summary>The <c>/ColorDodge</c> name.</summary>
    ColorDodge = 291,

    /// <summary>The <c>/ColorBurn</c> name.</summary>
    ColorBurn = 292,

    /// <summary>The <c>/HardLight</c> name.</summary>
    HardLight = 293,

    /// <summary>The <c>/SoftLight</c> name.</summary>
    SoftLight = 294,

    /// <summary>The <c>/Difference</c> name.</summary>
    Difference = 295,

    /// <summary>The <c>/Exclusion</c> name.</summary>
    Exclusion = 296,

    /// <summary>The <c>/Hue</c> name.</summary>
    Hue = 297,

    /// <summary>The <c>/Saturation</c> name.</summary>
    Saturation = 298,

    /// <summary>The <c>/Color</c> name.</summary>
    Color = 299,

    /// <summary>The <c>/DeviceGray</c> name.</summary>
    DeviceGray = 300,

    /// <summary>The <c>/DeviceRGB</c> name.</summary>
    DeviceRGB = 301,

    /// <summary>The <c>/DeviceCMYK</c> name.</summary>
    DeviceCMYK = 302,

    /// <summary>The <c>/CalGray</c> name.</summary>
    CalGray = 303,

    /// <summary>The <c>/CalRGB</c> name.</summary>
    CalRGB = 304,

    /// <summary>The <c>/Lab</c> name.</summary>
    Lab = 305,

    /// <summary>The <c>/ICCBased</c> name.</summary>
    ICCBased = 306,

    /// <summary>The <c>/Indexed</c> name.</summary>
    Indexed = 307,

    /// <summary>The <c>/Separation</c> name.</summary>
    Separation = 308,

    /// <summary>The <c>/DeviceN</c> name.</summary>
    DeviceN = 309,

    /// <summary>The <c>/RGB</c> name.</summary>
    RGB = 310,

    /// <summary>The <c>/CMYK</c> name.</summary>
    CMYK = 311,

    /// <summary>The <c>/Alternate</c> name.</summary>
    Alternate = 312,

    /// <summary>The <c>/WhitePoint</c> name.</summary>
    WhitePoint = 313,

    /// <summary>The <c>/BlackPoint</c> name.</summary>
    BlackPoint = 314,

    /// <summary>The <c>/Gamma</c> name.</summary>
    Gamma = 315,

    /// <summary>The <c>/Range</c> name.</summary>
    Range = 316,

    /// <summary>The <c>/All</c> name.</summary>
    All = 317,

    /// <summary>The <c>/Colorants</c> name.</summary>
    Colorants = 318,

    /// <summary>The <c>/Process</c> name.</summary>
    Process = 319,

    /// <summary>The <c>/Components</c> name.</summary>
    Components = 320,

    /// <summary>The <c>/Attributes</c> name.</summary>
    Attributes = 321,

    /// <summary>The <c>/NChannel</c> name.</summary>
    NChannel = 322,

    /// <summary>The <c>/PatternType</c> name.</summary>
    PatternType = 323,

    /// <summary>The <c>/PaintType</c> name.</summary>
    PaintType = 324,

    /// <summary>The <c>/TilingType</c> name.</summary>
    TilingType = 325,

    /// <summary>The <c>/XStep</c> name.</summary>
    XStep = 326,

    /// <summary>The <c>/YStep</c> name.</summary>
    YStep = 327,

    /// <summary>The <c>/ShadingType</c> name.</summary>
    ShadingType = 328,

    /// <summary>The <c>/Coords</c> name.</summary>
    Coords = 329,

    /// <summary>The <c>/Domain</c> name.</summary>
    Domain = 330,

    /// <summary>The <c>/Function</c> name.</summary>
    Function = 331,

    /// <summary>The <c>/Functions</c> name.</summary>
    Functions = 332,

    /// <summary>The <c>/Extend</c> name.</summary>
    Extend = 333,

    /// <summary>The <c>/Background</c> name.</summary>
    Background = 334,

    /// <summary>The <c>/AntiAlias</c> name.</summary>
    AntiAlias = 335,

    /// <summary>The <c>/BitsPerCoordinate</c> name.</summary>
    BitsPerCoordinate = 336,

    /// <summary>The <c>/BitsPerFlag</c> name.</summary>
    BitsPerFlag = 337,

    /// <summary>The <c>/VerticesPerRow</c> name.</summary>
    VerticesPerRow = 338,

    /// <summary>The <c>/FunctionType</c> name.</summary>
    FunctionType = 339,

    /// <summary>The <c>/BitsPerSample</c> name.</summary>
    BitsPerSample = 340,

    /// <summary>The <c>/Order</c> name.</summary>
    Order = 341,

    /// <summary>The <c>/Encode</c> name.</summary>
    Encode = 342,

    /// <summary>The <c>/C0</c> name.</summary>
    C0 = 343,

    /// <summary>The <c>/C1</c> name.</summary>
    C1 = 344,

    /// <summary>The <c>/Bounds</c> name.</summary>
    Bounds = 345,

    /// <summary>The <c>/Type0</c> name.</summary>
    Type0 = 346,

    /// <summary>The <c>/Type1</c> name.</summary>
    Type1 = 347,

    /// <summary>The <c>/MMType1</c> name.</summary>
    MMType1 = 348,

    /// <summary>The <c>/Type3</c> name.</summary>
    Type3 = 349,

    /// <summary>The <c>/TrueType</c> name.</summary>
    TrueType = 350,

    /// <summary>The <c>/CIDFontType0</c> name.</summary>
    CIDFontType0 = 351,

    /// <summary>The <c>/CIDFontType2</c> name.</summary>
    CIDFontType2 = 352,

    /// <summary>The <c>/BaseFont</c> name.</summary>
    BaseFont = 353,

    /// <summary>The <c>/FirstChar</c> name.</summary>
    FirstChar = 354,

    /// <summary>The <c>/LastChar</c> name.</summary>
    LastChar = 355,

    /// <summary>The <c>/Widths</c> name.</summary>
    Widths = 356,

    /// <summary>The <c>/FontDescriptor</c> name.</summary>
    FontDescriptor = 357,

    /// <summary>The <c>/Encoding</c> name.</summary>
    Encoding = 358,

    /// <summary>The <c>/ToUnicode</c> name.</summary>
    ToUnicode = 359,

    /// <summary>The <c>/DescendantFonts</c> name.</summary>
    DescendantFonts = 360,

    /// <summary>The <c>/CIDSystemInfo</c> name.</summary>
    CIDSystemInfo = 361,

    /// <summary>The <c>/DW</c> name.</summary>
    DW = 362,

    /// <summary>The <c>/DW2</c> name.</summary>
    DW2 = 363,

    /// <summary>The <c>/W2</c> name.</summary>
    W2 = 364,

    /// <summary>The <c>/CIDToGIDMap</c> name.</summary>
    CIDToGIDMap = 365,

    /// <summary>The <c>/Identity</c> name.</summary>
    Identity = 366,

    /// <summary>The <c>/Registry</c> name.</summary>
    Registry = 367,

    /// <summary>The <c>/Ordering</c> name.</summary>
    Ordering = 368,

    /// <summary>The <c>/Supplement</c> name.</summary>
    Supplement = 369,

    /// <summary>The <c>/FontName</c> name.</summary>
    FontName = 370,

    /// <summary>The <c>/FontFamily</c> name.</summary>
    FontFamily = 371,

    /// <summary>The <c>/FontStretch</c> name.</summary>
    FontStretch = 372,

    /// <summary>The <c>/FontWeight</c> name.</summary>
    FontWeight = 373,

    /// <summary>The <c>/Flags</c> name.</summary>
    Flags = 374,

    /// <summary>The <c>/FontBBox</c> name.</summary>
    FontBBox = 375,

    /// <summary>The <c>/ItalicAngle</c> name.</summary>
    ItalicAngle = 376,

    /// <summary>The <c>/Ascent</c> name.</summary>
    Ascent = 377,

    /// <summary>The <c>/Descent</c> name.</summary>
    Descent = 378,

    /// <summary>The <c>/Leading</c> name.</summary>
    Leading = 379,

    /// <summary>The <c>/CapHeight</c> name.</summary>
    CapHeight = 380,

    /// <summary>The <c>/XHeight</c> name.</summary>
    XHeight = 381,

    /// <summary>The <c>/StemV</c> name.</summary>
    StemV = 382,

    /// <summary>The <c>/StemH</c> name.</summary>
    StemH = 383,

    /// <summary>The <c>/AvgWidth</c> name.</summary>
    AvgWidth = 384,

    /// <summary>The <c>/MaxWidth</c> name.</summary>
    MaxWidth = 385,

    /// <summary>The <c>/MissingWidth</c> name.</summary>
    MissingWidth = 386,

    /// <summary>The <c>/FontFile</c> name.</summary>
    FontFile = 387,

    /// <summary>The <c>/FontFile2</c> name.</summary>
    FontFile2 = 388,

    /// <summary>The <c>/FontFile3</c> name.</summary>
    FontFile3 = 389,

    /// <summary>The <c>/Type1C</c> name.</summary>
    Type1C = 390,

    /// <summary>The <c>/CIDFontType0C</c> name.</summary>
    CIDFontType0C = 391,

    /// <summary>The <c>/OpenType</c> name.</summary>
    OpenType = 392,

    /// <summary>The <c>/CharSet</c> name.</summary>
    CharSet = 393,

    /// <summary>The <c>/CIDSet</c> name.</summary>
    CIDSet = 394,

    /// <summary>The <c>/Style</c> name.</summary>
    Style = 395,

    /// <summary>The <c>/Differences</c> name.</summary>
    Differences = 396,

    /// <summary>The <c>/BaseEncoding</c> name.</summary>
    BaseEncoding = 397,

    /// <summary>The <c>/StandardEncoding</c> name.</summary>
    StandardEncoding = 398,

    /// <summary>The <c>/WinAnsiEncoding</c> name.</summary>
    WinAnsiEncoding = 399,

    /// <summary>The <c>/MacRomanEncoding</c> name.</summary>
    MacRomanEncoding = 400,

    /// <summary>The <c>/MacExpertEncoding</c> name.</summary>
    MacExpertEncoding = 401,

    /// <summary>The <c>/FontMatrix</c> name.</summary>
    FontMatrix = 402,

    /// <summary>The <c>/CharProcs</c> name.</summary>
    CharProcs = 403,

    /// <summary>The <c>/Identity-H</c> name.</summary>
    IdentityH = 404,

    /// <summary>The <c>/Identity-V</c> name.</summary>
    IdentityV = 405,

    /// <summary>The <c>/CMap</c> name.</summary>
    CMap = 406,

    /// <summary>The <c>/CMapName</c> name.</summary>
    CMapName = 407,

    /// <summary>The <c>/UseCMap</c> name.</summary>
    UseCMap = 408,

    /// <summary>The <c>/WMode</c> name.</summary>
    WMode = 409,

    /// <summary>The <c>/FlateDecode</c> name.</summary>
    FlateDecode = 410,

    /// <summary>The <c>/Fl</c> name.</summary>
    Fl = 411,

    /// <summary>The <c>/LZWDecode</c> name.</summary>
    LZWDecode = 412,

    /// <summary>The <c>/LZW</c> name.</summary>
    LZW = 413,

    /// <summary>The <c>/ASCIIHexDecode</c> name.</summary>
    ASCIIHexDecode = 414,

    /// <summary>The <c>/AHx</c> name.</summary>
    AHx = 415,

    /// <summary>The <c>/ASCII85Decode</c> name.</summary>
    ASCII85Decode = 416,

    /// <summary>The <c>/A85</c> name.</summary>
    A85 = 417,

    /// <summary>The <c>/RunLengthDecode</c> name.</summary>
    RunLengthDecode = 418,

    /// <summary>The <c>/RL</c> name.</summary>
    RL = 419,

    /// <summary>The <c>/CCITTFaxDecode</c> name.</summary>
    CCITTFaxDecode = 420,

    /// <summary>The <c>/CCF</c> name.</summary>
    CCF = 421,

    /// <summary>The <c>/DCTDecode</c> name.</summary>
    DCTDecode = 422,

    /// <summary>The <c>/DCT</c> name.</summary>
    DCT = 423,

    /// <summary>The <c>/JBIG2Decode</c> name.</summary>
    JBIG2Decode = 424,

    /// <summary>The <c>/JPXDecode</c> name.</summary>
    JPXDecode = 425,

    /// <summary>The <c>/Crypt</c> name.</summary>
    Crypt = 426,

    /// <summary>The <c>/Predictor</c> name.</summary>
    Predictor = 427,

    /// <summary>The <c>/Colors</c> name.</summary>
    Colors = 428,

    /// <summary>The <c>/Columns</c> name.</summary>
    Columns = 429,

    /// <summary>The <c>/EarlyChange</c> name.</summary>
    EarlyChange = 430,

    /// <summary>The <c>/EndOfLine</c> name.</summary>
    EndOfLine = 431,

    /// <summary>The <c>/EncodedByteAlign</c> name.</summary>
    EncodedByteAlign = 432,

    /// <summary>The <c>/Rows</c> name.</summary>
    Rows = 433,

    /// <summary>The <c>/EndOfBlock</c> name.</summary>
    EndOfBlock = 434,

    /// <summary>The <c>/BlackIs1</c> name.</summary>
    BlackIs1 = 435,

    /// <summary>The <c>/DamagedRowsBeforeError</c> name.</summary>
    DamagedRowsBeforeError = 436,

    /// <summary>The <c>/ColorTransform</c> name.</summary>
    ColorTransform = 437,

    /// <summary>The <c>/JBIG2Globals</c> name.</summary>
    JBIG2Globals = 438,

    /// <summary>The <c>/Standard</c> name.</summary>
    Standard = 439,

    /// <summary>The <c>/OE</c> name.</summary>
    OE = 440,

    /// <summary>The <c>/UE</c> name.</summary>
    UE = 441,

    /// <summary>The <c>/EncryptMetadata</c> name.</summary>
    EncryptMetadata = 442,

    /// <summary>The <c>/CF</c> name.</summary>
    CF = 443,

    /// <summary>The <c>/StmF</c> name.</summary>
    StmF = 444,

    /// <summary>The <c>/StrF</c> name.</summary>
    StrF = 445,

    /// <summary>The <c>/EFF</c> name.</summary>
    EFF = 446,

    /// <summary>The <c>/CFM</c> name.</summary>
    CFM = 447,

    /// <summary>The <c>/AuthEvent</c> name.</summary>
    AuthEvent = 448,

    /// <summary>The <c>/V2</c> name.</summary>
    V2 = 449,

    /// <summary>The <c>/AESV2</c> name.</summary>
    AESV2 = 450,

    /// <summary>The <c>/AESV3</c> name.</summary>
    AESV3 = 451,

    /// <summary>The <c>/StdCF</c> name.</summary>
    StdCF = 452,

    /// <summary>The <c>/Recipients</c> name.</summary>
    Recipients = 453,

    /// <summary>The <c>/OCG</c> name.</summary>
    OCG = 454,

    /// <summary>The <c>/OCMD</c> name.</summary>
    OCMD = 455,

    /// <summary>The <c>/OCGs</c> name.</summary>
    OCGs = 456,

    /// <summary>The <c>/ON</c> name.</summary>
    ON = 457,

    /// <summary>The <c>/OFF</c> name.</summary>
    OFF = 458,

    /// <summary>The <c>/BaseState</c> name.</summary>
    BaseState = 459,

    /// <summary>The <c>/RBGroups</c> name.</summary>
    RBGroups = 460,

    /// <summary>The <c>/Locked</c> name.</summary>
    Locked = 461,

    /// <summary>The <c>/Usage</c> name.</summary>
    Usage = 462,

    /// <summary>The <c>/View</c> name.</summary>
    View = 463,

    /// <summary>The <c>/Design</c> name.</summary>
    Design = 464,

    /// <summary>The <c>/AllOn</c> name.</summary>
    AllOn = 465,

    /// <summary>The <c>/AnyOn</c> name.</summary>
    AnyOn = 466,

    /// <summary>The <c>/AnyOff</c> name.</summary>
    AnyOff = 467,

    /// <summary>The <c>/AllOff</c> name.</summary>
    AllOff = 468,

    /// <summary>The <c>/VE</c> name.</summary>
    VE = 469,

    /// <summary>The <c>/And</c> name.</summary>
    And = 470,

    /// <summary>The <c>/Or</c> name.</summary>
    Or = 471,

    /// <summary>The <c>/Not</c> name.</summary>
    Not = 472,

    /// <summary>The <c>/ListMode</c> name.</summary>
    ListMode = 473,

    /// <summary>The <c>/Configs</c> name.</summary>
    Configs = 474,

    /// <summary>The <c>/Event</c> name.</summary>
    Event = 475,

    /// <summary>The <c>/Category</c> name.</summary>
    Category = 476,

    /// <summary>The <c>/Print</c> name.</summary>
    Print = 477,

    /// <summary>The <c>/Export</c> name.</summary>
    Export = 478,

    /// <summary>The <c>/Zoom</c> name.</summary>
    Zoom = 479,

    /// <summary>The <c>/StructElem</c> name.</summary>
    StructElem = 480,

    /// <summary>The <c>/Pg</c> name.</summary>
    Pg = 481,

    /// <summary>The <c>/MCID</c> name.</summary>
    MCID = 482,

    /// <summary>The <c>/MCR</c> name.</summary>
    MCR = 483,

    /// <summary>The <c>/OBJR</c> name.</summary>
    OBJR = 484,

    /// <summary>The <c>/Obj</c> name.</summary>
    Obj = 485,

    /// <summary>The <c>/Alt</c> name.</summary>
    Alt = 486,

    /// <summary>The <c>/ActualText</c> name.</summary>
    ActualText = 487,

    /// <summary>The <c>/E</c> name.</summary>
    E = 488,

    /// <summary>The <c>/RoleMap</c> name.</summary>
    RoleMap = 489,

    /// <summary>The <c>/ParentTree</c> name.</summary>
    ParentTree = 490,

    /// <summary>The <c>/ClassMap</c> name.</summary>
    ClassMap = 491,

    /// <summary>The <c>/Artifact</c> name.</summary>
    Artifact = 492,

    /// <summary>The <c>/Span</c> name.</summary>
    Span = 493,

    /// <summary>The <c>/BPC</c> name.</summary>
    BPC = 494,

    /// <summary>The <c>/DP</c> name.</summary>
    DP = 495,

    /// <summary>The <c>/IM</c> name.</summary>
    IM = 496,

    /// <summary>The <c>/Volume</c> name.</summary>
    Volume = 497,

    /// <summary>The <c>/Trans</c> name.</summary>
    Trans = 498,

    /// <summary>The <c>/TA</c> name.</summary>
    TA = 499,

    /// <summary>The <c>/Synchronous</c> name.</summary>
    Synchronous = 500,

    /// <summary>The <c>/SS</c> name.</summary>
    SS = 501,

    /// <summary>The <c>/Condition</c> name.</summary>
    Condition = 502,

    /// <summary>The <c>/BaseVersion</c> name.</summary>
    BaseVersion = 503,

    /// <summary>The <c>/CT</c> name.</summary>
    CT = 504,

    /// <summary>The <c>/Sort</c> name.</summary>
    Sort = 505,

    /// <summary>The <c>/Schema</c> name.</summary>
    Schema = 506,

    /// <summary>The <c>/Folders</c> name.</summary>
    Folders = 507,

    /// <summary>The <c>/Free</c> name.</summary>
    Free = 508,

    /// <summary>The <c>/Child</c> name.</summary>
    Child = 509,

    /// <summary>The <c>/CI</c> name.</summary>
    CI = 510,

    /// <summary>The <c>/Views</c> name.</summary>
    Views = 511,

    /// <summary>The <c>/Threads</c> name.</summary>
    Threads = 512,

    /// <summary>The <c>/Mode</c> name.</summary>
    Mode = 513,

    /// <summary>The <c>/Repeat</c> name.</summary>
    Repeat = 514,

    /// <summary>The <c>/Operation</c> name.</summary>
    Operation = 515,

    /// <summary>The <c>/Poster</c> name.</summary>
    Poster = 516,

    /// <summary>The <c>/Start</c> name.</summary>
    Start = 517,

    /// <summary>The <c>/PageLayout</c> name.</summary>
    PageLayout = 518,

    /// <summary>The <c>/Private</c> name.</summary>
    Private = 519,

    /// <summary>The <c>/Legal</c> name.</summary>
    Legal = 520,

    /// <summary>The <c>/Dp</c> name.</summary>
    Dp = 521,

    /// <summary>The <c>/DPart</c> name.</summary>
    DPart = 522,

    /// <summary>The <c>/Rate</c> name.</summary>
    Rate = 523,

    /// <summary>The <c>/Duplex</c> name.</summary>
    Duplex = 524,

    /// <summary>The <c>/Enforce</c> name.</summary>
    Enforce = 525,

    /// <summary>The <c>/Instances</c> name.</summary>
    Instances = 526,

    /// <summary>The <c>/3DD</c> name.</summary>
    ThreeDD = 527,

    /// <summary>The <c>/ParentTreeNextKey</c> name.</summary>
    ParentTreeNextKey = 528,

    /// <summary>The <c>/BrotliDecode</c> name.</summary>
    BrotliDecode = 529,
}
