// Copyright (c) 2026 Glenn Watson. All rights reserved.
// Glenn Watson licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Buffers.Binary;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using OpenMcdf;
using PdfViewerLite.Tools.Packaging;

namespace PdfViewerLite.Tools.Signing;

/// <summary>Updates the generated MSI's file sizes and embedded cabinet in managed code.</summary>
internal static class MsiPayload
{
    /// <summary>Reads and updates the generated MSI without changing its installer schema.</summary>
    /// <param name="asset">The installer path.</param>
    /// <param name="payloads">Original hashes mapped to signed executables.</param>
    /// <param name="scratch">The temporary signing directory.</param>
    internal static void Replace(string asset, Dictionary<string, string> payloads, string scratch)
    {
        var folder = Path.Combine(scratch, $"cabinet-{Path.GetFileName(asset)}");
        _ = Directory.CreateDirectory(folder);
        using var archive = ZipFile.OpenRead(Path.ChangeExtension(asset, ".zip"));
        var sources = CreateSources(archive);
        using var root = RootStorage.Open(asset, FileMode.Open);
        var names = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var entry in root.EnumerateEntries())
        {
            names.Add(DecodeName(entry.Name), entry.Name);
        }

        var strings = ReadStrings(root, names);
        var table = ReadTable(root, names["File"]);
        var files = ReplaceFiles(table, strings, sources, payloads, folder);
        var cabinet = Path.Combine(folder, "signed.cab");
        CabinetWriter.Build(files, cabinet);
        using (var target = root.OpenStream(names["app.cab"]))
        using (var source = File.OpenRead(cabinet))
        {
            target.SetLength(0);
            source.CopyTo(target);
        }

        using (var tableStream = root.OpenStream(names["File"]))
        {
            tableStream.Write(table);
        }

        var storageClass = root.CLSID;
        root.Flush(consolidate: true);

        // OpenMcdf consolidation recreates the root directory entry without its MSI class identifier.
        root.CLSID = storageClass;
        root.Flush();
    }

    /// <summary>Maps the portable archive to the file identifiers generated by MsiBuilder.</summary>
    /// <param name="archive">The unsigned portable archive.</param>
    /// <returns>File identifiers mapped to archive entries.</returns>
    private static Dictionary<string, ZipArchiveEntry> CreateSources(ZipArchive archive)
    {
        var entries = new List<ZipArchiveEntry>(archive.Entries.Count);
        foreach (var entry in archive.Entries)
        {
            if (!entry.FullName.EndsWith('/'))
            {
                entries.Add(entry);
            }
        }

        entries.Sort(static (left, right) => StringComparer.OrdinalIgnoreCase.Compare(left.FullName, right.FullName));
        var sources = new Dictionary<string, ZipArchiveEntry>(StringComparer.Ordinal);
        for (var index = 0; index < entries.Count; index++)
        {
            var entry = entries[index];
            var key = Path.GetFileName(entry.FullName).Equals("pdfviewerlite.exe", StringComparison.OrdinalIgnoreCase) ? "fil_pdfviewerlite.exe" : $"fil_{index}";
            sources.Add(key, entry);
        }

        return sources;
    }

    /// <summary>Updates the generated File table and prepares payloads in cabinet sequence order.</summary>
    /// <param name="table">The column-major MSI File table.</param>
    /// <param name="strings">The MSI string pool.</param>
    /// <param name="sources">The original portable payloads.</param>
    /// <param name="payloads">Original hashes mapped to signed executables.</param>
    /// <param name="folder">The temporary cabinet directory.</param>
    /// <returns>Cabinet entries in MSI sequence order.</returns>
    /// <exception cref="InvalidDataException">The MSI differs from the generated installer format.</exception>
    private static List<(string Name, string Path)> ReplaceFiles(byte[] table, List<string> strings, Dictionary<string, ZipArchiveEntry> sources, Dictionary<string, string> payloads, string folder)
    {
        const int rowLength = 18;
        const int sizeColumnOffset = 6;
        const int sequenceColumnOffset = 16;
        if (table.Length % rowLength != 0)
        {
            throw new InvalidDataException("The MSI File table has an unsupported layout.");
        }

        var rows = table.Length / rowLength;
        var ordered = new SortedDictionary<int, (string Name, string Path)>();
        for (var row = 0; row < rows; row++)
        {
            var key = strings[BinaryPrimitives.ReadUInt16LittleEndian(table.AsSpan(row * sizeof(ushort)))];
            var path = Path.Combine(folder, key);
            if (key == "fil_license")
            {
                File.Copy("LICENSE", path, true);
            }
            else
            {
                var entry = sources[key];
                var originalSize = BinaryPrimitives.ReadInt32LittleEndian(table.AsSpan((rows * sizeColumnOffset) + (row * sizeof(int)))) ^ int.MinValue;
                if (entry.Length != originalSize)
                {
                    throw new InvalidDataException($"The original MSI size does not match the portable payload {entry.FullName}.");
                }

                CopyPayload(entry, path, payloads);
            }

            var size = checked((int)new FileInfo(path).Length) ^ int.MinValue;
            BinaryPrimitives.WriteInt32LittleEndian(table.AsSpan((rows * sizeColumnOffset) + (row * sizeof(int))), size);
            var sequence = BinaryPrimitives.ReadUInt16LittleEndian(table.AsSpan((rows * sequenceColumnOffset) + (row * sizeof(ushort)))) ^ 0x8000;
            ordered.Add(sequence, (key, path));
        }

        return [.. ordered.Values];
    }

    /// <summary>Copies signed executable bytes or preserves the original non-executable payload.</summary>
    /// <param name="entry">The unsigned archive entry.</param>
    /// <param name="target">The cabinet staging path.</param>
    /// <param name="payloads">Original hashes mapped to signed executables.</param>
    /// <exception cref="InvalidDataException">An executable has no signed replacement.</exception>
    private static void CopyPayload(ZipArchiveEntry entry, string target, Dictionary<string, string> payloads)
    {
        using var source = entry.Open();
        var hash = Convert.ToHexString(SHA256.HashData(source));
        if (payloads.TryGetValue(hash, out var signed))
        {
            File.Copy(signed, target, true);
        }
        else if (entry.FullName.EndsWith(".exe", StringComparison.OrdinalIgnoreCase) || entry.FullName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException($"No signed payload matches {entry.FullName}.");
        }
        else
        {
            entry.ExtractToFile(target, true);
        }
    }

    /// <summary>Reads the generated installer's two-byte string identifiers.</summary>
    /// <param name="root">The MSI compound storage.</param>
    /// <param name="names">Decoded stream names.</param>
    /// <returns>The string pool indexed by MSI identifier.</returns>
    /// <exception cref="InvalidDataException">The installer uses unsupported wide string identifiers.</exception>
    private static List<string> ReadStrings(RootStorage root, Dictionary<string, string> names)
    {
        using var pool = new BinaryReader(root.OpenStream(names["_StringPool"]));
        using var data = root.OpenStream(names["_StringData"]);
        var header = pool.ReadUInt32();
        if ((header & 0x80000000) != 0)
        {
            throw new InvalidDataException("The generated MSI must use two-byte string identifiers.");
        }

        var strings = new List<string> { string.Empty };
        while (pool.BaseStream.Position < pool.BaseStream.Length)
        {
            var length = pool.ReadUInt16();
            _ = pool.ReadUInt16();
            var bytes = new byte[length];
            data.ReadExactly(bytes);
            strings.Add(Encoding.Latin1.GetString(bytes));
        }

        return strings;
    }

    /// <summary>Decodes the MSI's compressed compound stream names.</summary>
    /// <param name="name">The compound stream name.</param>
    /// <returns>The MSI table or stream name.</returns>
    private static string DecodeName(string name)
    {
        const string alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz._";
        const int characterMask = 63;
        var text = new StringBuilder();
        foreach (var character in name)
        {
            if (character == 0x4840)
            {
                continue;
            }

            if (character is >= (char)0x3800 and < (char)0x4800)
            {
                var value = character - 0x3800;
                _ = text.Append(alphabet[value & characterMask]).Append(alphabet[value >> 6]);
            }
            else if (character is >= (char)0x4800 and < (char)0x4840)
            {
                _ = text.Append(alphabet[character - 0x4800]);
            }
            else
            {
                _ = text.Append(character);
            }
        }

        return text.ToString();
    }

    /// <summary>Reads a table while releasing its compound stream before consolidation.</summary>
    /// <param name="root">The compound storage.</param>
    /// <param name="name">The table stream name.</param>
    /// <returns>The table bytes.</returns>
    private static byte[] ReadTable(RootStorage root, string name)
    {
        using var source = root.OpenStream(name);
        using var buffer = new MemoryStream();
        source.CopyTo(buffer);
        return buffer.ToArray();
    }
}
