// Copyright (c) 2026 Glenn Watson. All rights reserved.
// Glenn Watson licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Globalization;
using System.Text;

namespace PdfViewerLite.Scripts;

/// <summary>
/// Turns the CxtVLC rows of T.814 Annex C into the decoder's packed lookup tables and the source text of
/// <c>JpxHtTables.cs</c>. <c>scripts/JpxHtTableGenerator.cs</c> includes this file, and the HyperPdfLibrary tests compile it
/// to check the checked-in tables against the rows.
/// </summary>
internal static class JpxHtTableBuilder
{
    /// <summary>The number of CxtVLC tables: one for the first row of quads and one for the others.</summary>
    internal const int TableCount = 2;

    /// <summary>The number of quad contexts.</summary>
    internal const int ContextCount = 8;

    /// <summary>The VLC bits a table lookup reads, the longest codeword length.</summary>
    internal const int LookupBits = 7;

    /// <summary>The entries of a packed table: every context times every seven-bit pattern.</summary>
    internal const int TableEntries = ContextCount << LookupBits;

    /// <summary>The shift of the u-offset bit in a packed entry.</summary>
    private const int OffsetShift = 3;

    /// <summary>The shift of rho in a packed entry.</summary>
    private const int RhoShift = 4;

    /// <summary>The shift of the EMB e1 bits in a packed entry.</summary>
    private const int OnesShift = 8;

    /// <summary>The shift of the EMB e-k bits in a packed entry.</summary>
    private const int KnownShift = 12;

    /// <summary>The number of fields in a row.</summary>
    private const int FieldCount = 7;

    /// <summary>The prefix of a table header line.</summary>
    private const string TableHeader = "[CxtVLC_table_";

    /// <summary>The prefix of a hexadecimal field.</summary>
    private const string HexPrefix = "0x";

    /// <summary>The entries on each line of the emitted source.</summary>
    private const int EntriesPerLine = 16;

    /// <summary>The text that starts <c>JpxHtTables.cs</c>.</summary>
    private const string Header = """
        // Copyright (c) 2026 Glenn Watson. All rights reserved.
        // Glenn Watson licenses this file to you under the MIT license.
        // See the LICENSE file in the project root for full license information.

        // <auto-generated>
        // Generated by scripts/JpxHtTableGenerator.cs from Data/T814CxtVlc.txt, the CxtVLC_table_0 and CxtVLC_table_1
        // rows of ITU-T T.814 (06/2019) | ISO/IEC 15444-15:2019, Annex C. Do not edit by hand.
        // </auto-generated>

        namespace HyperPdfLibrary.Graphics.Images.Jpx;

        /// <summary>
        /// The context VLC lookup tables of the HT cleanup pass (T.814 clause 7.3.5). Each table is indexed by the quad
        /// context times 128 plus the next seven VLC bits. An entry packs the codeword length (bits 0 to 2), the u-offset
        /// bit (bit 3), the significance pattern rho (bits 4 to 7), the EMB e1 bits (bits 8 to 11) and the EMB e-k bits
        /// (bits 12 to 15). An entry of zero marks bits that match no codeword.
        /// </summary>
        internal static class JpxHtTables
        {

        """;

    /// <summary>Parses the data file of Annex C rows.</summary>
    /// <param name="text">The file's text.</param>
    /// <returns>The rows of CxtVLC_table_0 and CxtVLC_table_1.</returns>
    /// <exception cref="InvalidDataException">A row is malformed or a table's row count differs from its header.</exception>
    internal static Row[][] ParseRows(string text)
    {
        var tables = new List<Row>[TableCount];
        var expected = new int[TableCount];
        var current = -1;
        foreach (var raw in text.Split('\n'))
        {
            var line = raw.Trim();
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            if (line.StartsWith(TableHeader, StringComparison.Ordinal))
            {
                current = line[TableHeader.Length] - '0';
                tables[current] = [];
                expected[current] = int.Parse(line[(line.IndexOf('=', StringComparison.Ordinal) + 1)..], CultureInfo.InvariantCulture);
                continue;
            }

            tables[current].Add(ParseRow(line, current));
        }

        var result = new Row[TableCount][];
        for (var t = 0; t < TableCount; t++)
        {
            if (tables[t].Count != expected[t])
            {
                throw new InvalidDataException($"CxtVLC_table_{t} lists {tables[t].Count} rows, the header says {expected[t]}.");
            }

            result[t] = [.. tables[t]];
        }

        return result;
    }

    /// <summary>Builds the packed lookup table of one CxtVLC table.</summary>
    /// <param name="rows">The table's rows.</param>
    /// <returns>The entries, indexed by context times 128 plus the next seven VLC bits; zero where no codeword matches.</returns>
    /// <exception cref="InvalidDataException">Two codewords of one context match the same VLC bits.</exception>
    internal static ushort[] BuildTable(Row[] rows)
    {
        var entries = new ushort[TableEntries];
        foreach (var row in rows)
        {
            var step = 1 << row.Length;
            for (var bits = row.Word; bits < 1 << LookupBits; bits += step)
            {
                var index = (row.Context << LookupBits) | bits;
                if (entries[index] != 0)
                {
                    throw new InvalidDataException($"Two codewords of context {row.Context} match the VLC bits {bits:X2}.");
                }

                entries[index] = Pack(in row);
            }
        }

        return entries;
    }

    /// <summary>Builds the source text of <c>JpxHtTables.cs</c>.</summary>
    /// <param name="rows">The rows of both tables.</param>
    /// <returns>The file's text, with line feeds.</returns>
    internal static string Emit(Row[][] rows)
    {
        var builder = new StringBuilder(Header);
        AppendTable(builder, "FirstRow", "Gets the table for quads in the first row of quads.", BuildTable(rows[0]));
        _ = builder.Append('\n');
        AppendTable(builder, "LaterRows", "Gets the table for quads in later rows of quads.", BuildTable(rows[1]));
        _ = builder.Append("}\n");
        return builder.ToString();
    }

    /// <summary>Packs a row: the codeword length, the u-offset bit, rho, e1 and e-k.</summary>
    /// <param name="row">The row.</param>
    /// <returns>The packed entry.</returns>
    private static ushort Pack(in Row row) =>
        (ushort)(row.Length | (row.Offset << OffsetShift) | (row.Rho << RhoShift) | (row.Ones << OnesShift) | (row.Known << KnownShift));

    /// <summary>Parses and checks one row of fields in the order of Annex C.</summary>
    /// <param name="line">The line.</param>
    /// <param name="table">The table the row belongs to.</param>
    /// <returns>The row.</returns>
    /// <exception cref="InvalidDataException">The row has the wrong number of fields or a field is out of range.</exception>
    private static Row ParseRow(string line, int table)
    {
        var fields = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (fields.Length != FieldCount)
        {
            throw new InvalidDataException($"Row '{line}' does not have {FieldCount} fields.");
        }

        var row = new Row(
            table,
            ParseField(fields[0]),
            ParseField(fields[1]),
            ParseField(fields[2]),
            ParseField(fields[3]),
            ParseField(fields[4]),
            ParseField(fields[5]),
            ParseField(fields[6]));
        if (!row.IsValid())
        {
            throw new InvalidDataException($"Row '{line}' is out of range.");
        }

        return row;
    }

    /// <summary>Parses a field written in decimal or, with the 0x prefix, hexadecimal.</summary>
    /// <param name="field">The field.</param>
    /// <returns>The value.</returns>
    private static int ParseField(string field) =>
        field.StartsWith(HexPrefix, StringComparison.Ordinal)
            ? int.Parse(field.AsSpan(HexPrefix.Length), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture)
            : int.Parse(field, CultureInfo.InvariantCulture);

    /// <summary>Appends one table as a span property.</summary>
    /// <param name="builder">The builder.</param>
    /// <param name="name">The property name.</param>
    /// <param name="summary">The property summary.</param>
    /// <param name="entries">The table.</param>
    private static void AppendTable(StringBuilder builder, string name, string summary, ushort[] entries)
    {
        _ = builder.Append("    /// <summary>").Append(summary).Append("</summary>\n");
        _ = builder.Append("    internal static ReadOnlySpan<ushort> ").Append(name).Append(" => [\n");
        for (var i = 0; i < entries.Length; i += EntriesPerLine)
        {
            _ = builder.Append("       ");
            for (var j = i; j < i + EntriesPerLine; j++)
            {
                _ = builder.Append(" 0x").Append(entries[j].ToString("X4", CultureInfo.InvariantCulture)).Append(',');
            }

            _ = builder.Append('\n');
        }

        _ = builder.Append("    ];\n");
    }

    /// <summary>One row of a CxtVLC table: the fields of an Annex C entry.</summary>
    /// <param name="Table">0 for CxtVLC_table_0 (first row of quads), 1 for CxtVLC_table_1.</param>
    /// <param name="Context">The quad context c_q.</param>
    /// <param name="Rho">The significance pattern rho_q.</param>
    /// <param name="Offset">The u-offset bit u_off.</param>
    /// <param name="Known">The EMB known-bit pattern e_k.</param>
    /// <param name="Ones">The EMB value pattern e_1.</param>
    /// <param name="Word">The codeword w as a little-endian integer: its lowest bit comes first in the VLC stream.</param>
    /// <param name="Length">The codeword length l_w in bits.</param>
    internal readonly record struct Row(int Table, int Context, int Rho, int Offset, int Known, int Ones, int Word, int Length)
    {
        /// <summary>The largest value of a four-bit field.</summary>
        private const int NibbleLimit = 15;

        /// <summary>Checks that every field is in its range.</summary>
        /// <returns><see langword="true"/> when the row can be packed.</returns>
        internal bool IsValid() => FieldsFit() && CodewordFits();

        /// <summary>Checks the context, the flag and the three four-bit patterns.</summary>
        /// <returns><see langword="true"/> when they are in range.</returns>
        private bool FieldsFit() =>
            Context is >= 0 and < ContextCount
            && Offset is 0 or 1
            && Rho is >= 0 and <= NibbleLimit
            && Known is >= 0 and <= NibbleLimit
            && Ones is >= 0 and <= NibbleLimit;

        /// <summary>Checks that the codeword is one to seven bits long and fits its length.</summary>
        /// <returns><see langword="true"/> when it does.</returns>
        private bool CodewordFits() => Length is >= 1 and <= LookupBits && Word >= 0 && Word < 1 << Length;
    }
}
