// Copyright (c) 2026 Glenn Watson. All rights reserved.
// Glenn Watson licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Globalization;
using System.Text;
using HyperPdfLibrary.Objects;

namespace PdfViewerLite.Scripts;

/// <summary>Generates a UTF-8 spelling blob and a minimal perfect hash from the fixed known-name ids.</summary>
internal static class KnownNameTableBuilder
{
    /// <summary>The largest displacement searched before rejecting an unsuitable name list.</summary>
    private const int MaxDisplacement = 1_000_000;

    /// <summary>The values per generated data line.</summary>
    private const int ValuesPerLine = 16;

    /// <summary>The spelling marker in the enum documentation.</summary>
    private const string SpellingStart = "<c>/";

    /// <summary>The end of a documented spelling.</summary>
    private const string SpellingEnd = "</c>";

    /// <summary>Builds deterministic source tables from the documented enum spellings.</summary>
    /// <param name="source">The known-name enum source.</param>
    /// <returns>The generated source.</returns>
    internal static string Emit(string source)
    {
        var spellings = Parse(source);
        var tables = Build(spellings);
        var output = new StringBuilder();
        _ = output.AppendLine("// Copyright (c) 2026 Glenn Watson. All rights reserved.");
        _ = output.AppendLine("// Glenn Watson licenses this file to you under the MIT license.");
        _ = output.AppendLine("// See the LICENSE file in the project root for full license information.");
        _ = output.AppendLine();
        _ = output.AppendLine("// <auto-generated/> by scripts/KnownNameTableGenerator.cs from KnownName.cs.");
        _ = output.AppendLine();
        _ = output.AppendLine("namespace HyperPdfLibrary.Objects;");
        _ = output.AppendLine();
        _ = output.AppendLine("/// <summary>A single UTF-8 spelling blob and collision-free known-name lookup tables.</summary>");
        _ = output.AppendLine("internal static class KnownNameSpellings");
        _ = output.AppendLine("{");
        _ = output.AppendLine(CultureInfo.InvariantCulture, $"    internal const int Count = {spellings.Length};");
        AppendBlob(output, spellings);
        AppendTable(output, "Offsets", "ushort", tables.Offsets);
        AppendTable(output, "Displacements", "int", tables.Displacements);
        AppendTable(output, "Slots", "ushort", tables.Slots);
        _ = output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>Reads the spelling and contiguous id of each enum member.</summary>
    /// <param name="source">The enum source.</param>
    /// <returns>The spellings in id order, including the empty sentinel.</returns>
    /// <exception cref="InvalidDataException">The enum ids are not contiguous.</exception>
    private static string[] Parse(string source)
    {
        var spellings = new List<string> { string.Empty };
        var spelling = string.Empty;
        using var reader = new StringReader(source);
        while (reader.ReadLine() is { } line && !line.Equals("}", StringComparison.Ordinal))
        {
            var start = line.IndexOf(SpellingStart, StringComparison.Ordinal);
            if (start >= 0)
            {
                start += SpellingStart.Length;
                spelling = line[start..line.IndexOf(SpellingEnd, start, StringComparison.Ordinal)];
            }
            else if (spelling.Length > 0 && line.Contains('=', StringComparison.Ordinal))
            {
                var id = int.Parse(line.AsSpan(line.IndexOf('=', StringComparison.Ordinal) + 1).Trim().TrimEnd(','), CultureInfo.InvariantCulture);
                if (id != spellings.Count)
                {
                    throw new InvalidDataException("Known-name ids must remain contiguous and stable.");
                }

                spellings.Add(spelling);
                spelling = string.Empty;
            }
        }

        return [.. spellings];
    }

    /// <summary>Assigns every known spelling to its own hash slot.</summary>
    /// <param name="spellings">The spellings in id order.</param>
    /// <returns>The offsets, bucket displacements and occupied slots.</returns>
    /// <exception cref="InvalidDataException">The sampled spelling hashes collide.</exception>
    private static Tables Build(string[] spellings)
    {
        var size = spellings.Length - 1;
        var buckets = new List<Entry>[size];
        for (var i = 0; i < size; i++)
        {
            buckets[i] = [];
        }

        var offsets = new int[spellings.Length + 1];
        var hashes = new HashSet<uint>();
        for (var id = 1; id < spellings.Length; id++)
        {
            var hash = KnownNameHash.Hash(Encoding.UTF8.GetBytes(spellings[id]));
            if (!hashes.Add(hash))
            {
                throw new InvalidDataException("Known-name edge hashes collide; include more spelling bytes in the hash.");
            }

            buckets[hash % (uint)size].Add(new(id, hash));
            offsets[id + 1] = offsets[id] + Encoding.UTF8.GetByteCount(spellings[id]);
        }

        var order = new Bucket[size];
        for (var i = 0; i < order.Length; i++)
        {
            order[i] = new(i, buckets[i]);
        }

        Array.Sort(order, static (left, right) =>
        {
            var count = right.Entries.Count.CompareTo(left.Entries.Count);
            return count != 0 ? count : left.Index.CompareTo(right.Index);
        });
        var tables = new Tables(offsets, new int[size], new int[size]);
        foreach (var bucket in order)
        {
            AssignBucket(bucket.Entries, bucket.Index, tables);
        }

        return tables;
    }

    /// <summary>Finds a displacement whose positions are distinct and still free.</summary>
    /// <param name="entries">The names in the bucket.</param>
    /// <param name="index">The bucket index.</param>
    /// <param name="tables">The tables being filled.</param>
    /// <exception cref="InvalidDataException">No bounded perfect hash fits the names.</exception>
    private static void AssignBucket(List<Entry> entries, int index, Tables tables)
    {
        if (entries.Count == 0)
        {
            return;
        }

        if (entries.Count == 1)
        {
            var slot = Array.IndexOf(tables.Slots, 0);
            tables.Displacements[index] = -slot - 1;
            tables.Slots[slot] = entries[0].Id;
            return;
        }

        var positions = new int[entries.Count];
        for (var displacement = 1; displacement < MaxDisplacement; displacement++)
        {
            if (!TryPositions(entries, displacement, tables.Slots, positions))
            {
                continue;
            }

            tables.Displacements[index] = displacement;
            for (var i = 0; i < entries.Count; i++)
            {
                tables.Slots[positions[i]] = entries[i].Id;
            }

            return;
        }

        throw new InvalidDataException("No bounded perfect-hash displacement was found.");
    }

    /// <summary>Checks whether a displacement fits an entire bucket.</summary>
    /// <param name="entries">The bucket entries.</param>
    /// <param name="displacement">The proposed displacement.</param>
    /// <param name="slots">The occupied slots.</param>
    /// <param name="positions">Receives the proposed positions.</param>
    /// <returns>Whether every position is distinct and free.</returns>
    private static bool TryPositions(List<Entry> entries, int displacement, int[] slots, int[] positions)
    {
        for (var i = 0; i < entries.Count; i++)
        {
            var slot = (int)(KnownNameHash.Displace(entries[i].Hash, displacement) % (uint)slots.Length);
            if (slots[slot] != 0 || positions.AsSpan(0, i).Contains(slot))
            {
                return false;
            }

            positions[i] = slot;
        }

        return true;
    }

    /// <summary>Emits the UTF-8 literal without allocating separate runtime spellings.</summary>
    /// <param name="output">The generated source.</param>
    /// <param name="spellings">The spellings in id order.</param>
    private static void AppendBlob(StringBuilder output, string[] spellings)
    {
        _ = output.AppendLine();
        _ = output.Append("    internal static ReadOnlySpan<byte> Blob => \"");
        foreach (var spelling in spellings)
        {
            _ = output.Append(spelling.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal));
        }

        _ = output.AppendLine("\"u8;");
    }

    /// <summary>Emits a span table backed by compiler-generated static data.</summary>
    /// <param name="output">The generated source.</param>
    /// <param name="name">The table name.</param>
    /// <param name="elementType">The table element type.</param>
    /// <param name="values">The values.</param>
    private static void AppendTable(StringBuilder output, string name, string elementType, int[] values)
    {
        _ = output.AppendLine();
        _ = output.AppendLine(CultureInfo.InvariantCulture, $"    internal static ReadOnlySpan<{elementType}> {name} =>");
        _ = output.AppendLine("    [");
        for (var i = 0; i < values.Length; i++)
        {
            if (i % ValuesPerLine == 0)
            {
                _ = output.Append("        ");
            }

            _ = output.Append(CultureInfo.InvariantCulture, $"{values[i]},");
            _ = output.Append((uint)i % ValuesPerLine == ValuesPerLine - 1 || i == values.Length - 1 ? "\n" : " ");
        }

        _ = output.AppendLine("    ];");
    }

    /// <summary>A known name and its stable spelling hash.</summary>
    /// <param name="Id">The fixed name id.</param>
    /// <param name="Hash">The spelling hash.</param>
    private readonly record struct Entry(int Id, uint Hash);

    /// <summary>A hash bucket and its stable index.</summary>
    /// <param name="Index">The bucket index.</param>
    /// <param name="Entries">The names in the bucket.</param>
    private readonly record struct Bucket(int Index, List<Entry> Entries);

    /// <summary>The generated perfect-hash data.</summary>
    /// <param name="Offsets">The spelling offsets in the UTF-8 blob.</param>
    /// <param name="Displacements">The displacement of each hash bucket.</param>
    /// <param name="Slots">The name id in every collision-free slot.</param>
    private sealed record Tables(int[] Offsets, int[] Displacements, int[] Slots);
}
