// Copyright (c) 2026 Glenn Watson. All rights reserved.
// Glenn Watson licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using PdfViewerLite.Core.Licences;

namespace PdfViewerLite.App.Services;

/// <summary>
/// Reads the third-party notices that the build embeds in the app (<c>licenses/notices/PdfViewerLite.App.md</c>,
/// generated by <c>scripts/GenerateThirdPartyNotices.cs</c>). The file is read once and shared.
/// </summary>
internal static class LicenceNotices
{
    /// <summary>The name of the embedded resource.</summary>
    internal const string ResourceName = "PdfViewerLite.ThirdPartyNotices.md";

    /// <summary>The notices once read.</summary>
    private static NoticeDocument? _document;

    /// <summary>Gets the notices embedded in the app.</summary>
    /// <returns>The notices; empty when the resource is missing.</returns>
    internal static NoticeDocument Load() => Volatile.Read(ref _document) ?? Read();

    /// <summary>Reads the embedded text and publishes the parsed notices.</summary>
    /// <returns>The notices.</returns>
    private static NoticeDocument Read()
    {
        using var stream = typeof(LicenceNotices).Assembly.GetManifestResourceStream(ResourceName);
        var document = NoticeDocument.Empty;
        if (stream is not null)
        {
            using var reader = new StreamReader(stream);
            document = NoticeDocument.Parse(reader.ReadToEnd());
        }

        return Interlocked.CompareExchange(ref _document, document, null) ?? document;
    }
}
